name: PublishSupport

on:
  push:
    branches: ['main']
    paths: ['support/**']

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: latest
          
      - name: Install npm dependencies
        working-directory: support/vscode
        run: npm install

      - name: Publish VSCode Extension
        working-directory: support/vscode
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          npm run vscode:publish 2>&1 | tee tmp.log
          if grep -qE 'ohkami-rs.uibeam v[0-9]+\.[0-9]+\.[0-9]+ already exists\.' tmp.log; then
            echo "already published version, skipping publish..."
            exit 0
          elif grep -qE 'Published ohkami-rs.uibeam v[0-9]+\.[0-9]+\.[0-9]+\.' tmp.log; then
            echo "successfully published!"
            exit 0
          else
            echo "retrying publish..."
            npm run vscode:publish
          fi
